
name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout el código desde GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # Configura PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Puedes cambiar a la versión que usas en tu proyecto
        extensions: mbstring, bcmath, xml, curl
        coverage: xdebug

    # Instalar dependencias de Composer
    - name: Install Composer dependencies
      run: |
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install --no-interaction

    # Copiar el archivo .env para las pruebas
    - name: Copy .env file
      run: cp .env.example .env

    # Generar la clave de la aplicación Laravel
    - name: Generate Laravel key
      run: php artisan key:generate

    # Ejecutar las migraciones (si es necesario)
    - name: Run migrations
      run: php artisan migrate --env=testing

    # Ejecutar las pruebas de PHPUnit
    - name: Run PHPUnit tests
      run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
