name: Build and push Node.js formatter image
on:
  push:
    branches: ['main']
    paths: ['Dockerfile'] # Se ejecuta solo si se modifica el Dockerfile.

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Log in to DockerHub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Node.js formatter image
        uses: docker/build-push-action@v6.9.0
        with:
          context: . # Construye desde el directorio raíz donde está el Dockerfile
          push: true
          tags: finanssoreal/node-lts-prettier2:latest
