name: codigo-formateado
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
jobs:
  formatting-checks:
    runs-on: ubuntu-latest
    container:
      image: romeo188/node-lts-prettier
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check JS file formatting
        run: prettier . --check
